name: flutter_bloc_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  formz: ^0.7.0
  http: ^1.2.1
  stream_transform: ^2.1.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
